version: "3.1"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      DB_HOST: db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "e-cga"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    expose:
      # Opens port 3306 on the container
      - "3307"
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql
